version: '2'
services:
  akhq:
    image: tchiotludo/akhq:0.14.1
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "103.142.139.174:10400"
    #                bootstrap.servers: "kafka:9092"
    ports:
      - 17020:8080
