# ============================================================================
# Add by yuvytung
# This file use for server-dev : dev.catiny.com
# ============================================================================

version: '2'
services:
  catinymessenger-app:
    extends:
      file: catiny-messenger.yml
      service: catinymessenger-app
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@dev.catiny.com:10200/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@dev.catiny.com:10200/config
      - JHIPSTER_SLEEP=80 # gives time for uaa and the Cassandra cluster to start and execute the migration scripts
  catinymessenger-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: catinymessenger-cassandra
    volumes:
      - /root/volumes/jhipster/CatinyMessenger/cassandra/:/var/lib/cassandra/data
  catinymessenger-cassandra-node:
    extends:
      file: cassandra-cluster.yml
      service: catinymessenger-cassandra-node
    volumes:
      - /root/volumes/jhipster/CatinyMessenger/cassandra-node-1/:/var/lib/cassandra/data
  catinymessenger-cassandra-migration:
    extends:
      file: cassandra-cluster.yml
      service: catinymessenger-cassandra-migration
  catinymessenger-redis:
    extends:
      file: redis.yml
      service: catinymessenger-redis
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_PRIVATE://kafka:9092,LISTENER_PUBLIC://dev.catiny.com:10400
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/dev-config/
