version: '2'
services:
  catinymessenger-app:
    extends:
      file: catiny-messenger.yml
      service: catinymessenger-app
  catinymessenger-cassandra:
    extends:
      file: cassandra.yml
      service: catinymessenger-cassandra
  #  catinymessenger-cassandra:
  #    extends:
  #      file: cassandra-cluster.yml
  #      service: catinymessenger-cassandra
  #  catinymessenger-cassandra-node:
  #    image: cassandra:3.11.5
  #    environment:
  #      - CASSANDRA_SEEDS=catinymessenger-cassandra
  catinymessenger-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: catinymessenger-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
  catinymessenger-redis:
    extends:
      file: redis.yml
      service: catinymessenger-redis
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
#  jhipster-registry:
#    extends:
#      file: jhipster-registry.yml
#      service: jhipster-registry
#    environment:
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
