version: '2'
services:
  catinymessenger-cassandra:
    image: cassandra:3.11.5
    # volumes:
    #     - ~/volumes/jhipster/CatinyMessenger/cassandra/:/var/lib/cassandra/data
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  catinymessenger-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=catinymessenger-cassandra
  catinymessenger-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: catinymessenger-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
